version: "3"

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"
  hawk-catcher:
    image: "hawk.catcher"
    build: .
    ports:
      - "3000:3000"
    volumes:
      - $PWD/docker-config.json:/app/docker-config.json:ro
    depends_on:
      - rabbitmq
