name: Docker Image CI

on: [push]

env:
  DOCKER_REPO: ${{ secrets.DOCKER_USERNAME }}/hawk-collector

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Build and push docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ env.DOCKER_REPO }}
          tag_with_ref: true
          push: ${{ endsWith(github.ref, '/stage') || endsWith(github.ref, '/prod') }}

      - name: Deploy stage
        if: endsWith(github.ref, '/stage')
        run: |
          curl --user ${{ secrets.DEPLOY_HAWK_STAGE_AUTH }} ${{ secrets.DEPLOY_HAWK_STAGE_ADDRESS }}?image=${{ env.DOCKER_REPO }}:stage
