name: Update hawk.mono

on: [push]

jobs:

  build:

    runs-on: ubuntu-18.04

    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.HAWK_MONO_REPO_ACCESS_TOKEN }}
          event-type: my-event
          repository: codex-team/hawk.mono
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'